### PR TITLE
Documentation: Fix cmesh doxygen

### LINKED ISSUE #1743: Fix doxygen for cmesh
# Bug report

fix all doxygen errors related to files in the cmesh-folder 

**Describe the bug**
A clear and concise description of what the bug/unexpected behaviour is.

**To Reproduce**
Which command did you run/which function did you call?

**Expected behavior**

**Log files**
- If possible, add any output and error messages that you got
- Please upload the `config.log` file (when building with autotools)
- For failing tests, please upload the `test-suite.log` file (when building with autotools)
- When building with CMake please upload
  - `CMakeCache.txt`
  - `CMakeFiles/CMakeError.log`
  - `CMakeFiles/CMakeOutput.log`
  - `Testing/Temporary/FailedTest.log` (for failing tests)
  - `Testing/Temporary/LastTestsFailed.log` (for failing tests)

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04, Windows 11]
 - Compiler: [e.g., gcc, icc, mpicc]
 - Compiler version: [e.g. the output of 'gcc --version']
 - MPI version (if MPI is used): [The output of 'mpirun --version' or 'mpiexec --version']
 
**Estimated priority**
Which of these is most applicable (remove the others):

"Priority: high"  Should be solved as soon as possible 

"Priority: medium"  Should be solved within half a year 

"Priority: low" Should be solved eventually

**Additional context**

### PR DESCRIPTION
**Pull request by Davknapp**
**_Describe your changes here:_**
fixes all t8_cmesh/* related doxygen errors. Use doxygen version 1.13.2 to support modern C++ features like [[maybe_unused]]

Closes #1743 

**_All these boxes must be checked by the AUTHOR before requesting review:_**
- [x] The PR is *small enough* to be reviewed easily. If not, consider splitting up the changes in multiple PRs.
- [x] The title starts with one of the following prefixes: `Documentation:`, `Bugfix:`, `Feature:`, `Improvement:` or `Other:`.
- [x] If the PR is related to an issue, make sure to link it.
- [x] The author made sure that, as a reviewer, he/she would check all boxes below.

**_All these boxes must be checked by the REVIEWERS before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is *fully understood, bug free, well-documented and well-structured*.
#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually.
- [ ] The code follows the [t8code coding guidelines](https://github.com/DLR-AMR/t8code/wiki/Coding-Guideline).
- [ ] New source/header files are properly added to the CMake files.
- [ ] The code is well documented. In particular, all function declarations, structs/classes and their members have a proper doxygen documentation.
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue).
#### Tests
- [ ] The code is covered in an existing or new test case using Google Test.
- [ ] The code coverage of the project (reported in the CI) should not decrease. If coverage is decreased, make sure that this is reasonable and acceptable.
- [ ] Valgrind doesn't find any bugs in the new code. [This script](https://github.com/DLR-AMR/t8code/blob/main/scripts/check_valgrind.sh) can be used to check for errors; see also this [wiki article](https://github.com/DLR-AMR/t8code/wiki/Debugging-with-valgrind).

If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually).
#### Scripts and Wiki
- [ ] If a new directory with source files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example or tutorial and a Wiki article.
#### License
- [ ] The author added a BSD statement to `doc/` (or already has one).

### CODE REVIEW

File: src/t8_cmesh/t8_cmesh_commit.cxx [hunk 1]
```diff
@@ -506,6 +512,12 @@ t8_cmesh_commit_partitioned_new (t8_cmesh_t cmesh, sc_MPI_Comm comm)
 #endif
 }
 
+/**
+ * \brief Commit a cmesh from stash.
```
Comment (sandro-elsweijer) [inline src/t8_cmesh/t8_cmesh_commit.cxx]:
```suggestion
 * \brief Commit a cmesh from stash.
```
We should maybe document if we want to use \brief or not

File: src/t8_cmesh/t8_cmesh_copy.h [hunk 2]
```diff
@@ -34,6 +34,13 @@
 
 T8_EXTERN_C_BEGIN ();
 
+/**
+ * Copy the coarse mesh from cmesh_from to cmesh.
```
Comment (sandro-elsweijer) [inline src/t8_cmesh/t8_cmesh_copy.h]:
```suggestion
 * Copy the coarse mesh from \a cmesh_from to \a cmesh.
```

File: src/t8_cmesh/t8_cmesh_examples.cxx [hunk 3]
```diff
@@ -38,8 +38,8 @@
 #include <t8_schemes/t8_default/t8_default_c_interface.h> /* default refinement scheme. */
 
 /**
- * \brief This function calculates an 'equal' partition for the cmesh based on the \var number of trees supplied
- *  and stores the computed partition range within the \var cmesh.
+ * \brief This function calculates an 'equal' partition for the cmesh based on the \a number_trees supplied
```
Comment (sandro-elsweijer) [inline src/t8_cmesh/t8_cmesh_examples.cxx]:
```suggestion
 * Calculate an 'equal' partition for the cmesh based on the \a number_trees supplied
```

File: src/t8_cmesh/t8_cmesh_examples.h [hunk 4]
```diff
@@ -40,22 +40,21 @@ T8_EXTERN_C_BEGIN ();
...
 
 /** Constructs a cmesh from a given p8est_connectivity structure.
  * \param[in]       conn       The p8est connectivity.
  * \param[in]       comm       mpi communicator to be used with the new cmesh.
- * \param[in]       do_dup     Flag whether the communicator shall be duplicated or not.
  * \param[in]       do_partition Flag whether the cmesh should be partitioned or not.
  * \return          A t8_cmesh structure that holds the same connectivity information
  *                  as \a conn.
  * \note This function requires that p4est is initialized. Make sure to call
- * \ref p4est_init before using this routine. If this is not the case, a
```
Comment (sandro-elsweijer) [inline src/t8_cmesh/t8_cmesh_examples.h:57]: Why shouldn't we reference the function?

File: src/t8_cmesh/t8_cmesh_examples.h [hunk 5]
```diff
@@ -107,15 +105,16 @@ t8_cmesh_new_hypercube (t8_eclass_t eclass, sc_MPI_Comm comm, int do_bcast, int
  * \return                      A committed t8_cmesh structure with 
  *                              \a polygons_x * \a polygons_z * \a polygons_y many 
  *                              sub-hypercubes of class \a eclass.
+ * 
  * \note \a boundary must point to an array with 3*8 (3D), 3*4 (2D), 3*2 (1D), or 3 (0D) entries.
- * \note Every sub-hypercube contains different number of trees depending on \a eclass.
```
Comment (sandro-elsweijer) [inline src/t8_cmesh/t8_cmesh_examples.h:111]: Does \note not work?
https://www.doxygen.nl/manual/commands.html#cmdnote

File: src/t8_cmesh/t8_cmesh_examples.h [hunk 6]
```diff
@@ -151,11 +150,11 @@ t8_cmesh_new_hypercube_pad (const t8_eclass_t eclass, sc_MPI_Comm comm, const do
  *                              \a polygons_x * \a polygons_z * \a polygons_y many 
  *                              sub-hypercubes of class \a eclass.
  * \note \a boundary must point to an array with 3*8 (3D), 3*4 (2D), 3*2 (1D), or 3 (0D) entries.
- * \note Every sub-hypercube contains different number of trees depending on \a eclass.
```
Comment (sandro-elsweijer) [inline src/t8_cmesh/t8_cmesh_examples.h:154]: same here

File: src/t8_cmesh/t8_cmesh_netcdf.c [hunk 7]
```diff
@@ -43,59 +43,68 @@ These functions write a file in the netCDF-format which represents the given 2D-
 #include <t8_cmesh/t8_cmesh_types.h>
 #include <t8_schemes/t8_scheme.h>
 
-/* Contains all Variables used in order to work with the NetCDF-File */
+/**
+ * \struct t8_cmesh_netcdf_context_t
```
Comment (sandro-elsweijer) [inline src/t8_cmesh/t8_cmesh_netcdf.c]: Sometimes we use \stuct and sometimes we do not

File: src/t8_cmesh/t8_cmesh_trees.cxx [hunk 8]
```diff
@@ -213,9 +213,25 @@ t8_cmesh_trees_start_part (const t8_cmesh_trees_t trees, const int proc, const t
...
+ * Local identifier for the partition ghost.
+ *
+ * \var t8_part_ghost_id_and_num_atts::global_id
+ * Global identifier for the partition ghost.
+ *
+ * \var t8_part_ghost_id_and_num_atts::num_attributes
+ * Number of attributes associated with the partition ghost.
+ *
+ * \var t8_part_ghost_id_and_num_atts::attribute_offset
+ * Offset to the attributes associated with the partition ghost.
```
Comment (sandro-elsweijer) [inline src/t8_cmesh/t8_cmesh_trees.cxx]: Would it also be possible to out the comments after the variables themselves instead of the struct documentation?

File: src/t8_cmesh/t8_cmesh_types.h [hunk 9]
```diff
@@ -228,34 +239,41 @@ typedef struct t8_attribute_info
...
+  t8_locidx_t num_trees;      /**< The number of trees */
+  t8_locidx_t num_ghosts;     /**< The number of ghosts */
 } t8_part_tree_struct_t;
 
 /* TODO: Extend this structure with meaningful entries.
  *       Maybe the number of shipped trees per process is useful?
  */
-/** This struct is used to profile cmesh algorithms.
+/** 
+ * t8_cprofile_struct_t
```
Comment (sandro-elsweijer) [inline src/t8_cmesh/t8_cmesh_types.h]: do we add the name or not? I think not because it is easier, we do not have to change it if the class name changes and it clutters the outpot when hovering over a variable with the mouse

**Review by sandro-elsweijer — CHANGES_REQUESTED** [review]
Thank you very much!

Most of this is clear, but we probably have to document how we want to document things.
- Do we use /** or /**< for variables?
- Do we use \brief?
- Do we state the struct/class name in their doxygen comment?

1. I think /** is easier and more consistent with the rest from doxygen
2. Why should we use \brief? I see no advantages
3. I think it clutters the documentation and adds no more information and we would need to keep track of it if the class name itself changes, so no.

Just my humble opinion, maybe I have some false assumptions about doxygen :)

File: src/t8_cmesh/t8_cmesh_types.h (hunk 9 above)
Comment (Davknapp) [reply src/t8_cmesh/t8_cmesh_types.h]: Ah yes, it is not necessary to add them. I was trying to fix a warning using \struct struct_name, but it is not necessary to use the name here. Thanks for catching that.

File: src/t8_cmesh/t8_cmesh_trees.cxx (hunk 8 above)
Comment (Davknapp) [reply src/t8_cmesh/t8_cmesh_trees.cxx]: yes, I can do that.

File: src/t8_cmesh/t8_cmesh_examples.h (hunk 4 above)
Comment (Davknapp) [reply src/t8_cmesh/t8_cmesh_examples.h:57]: because we do not create the p4est-doxygen with the t8code-doxygen documentation and won't be able to find it.

File: src/t8_cmesh/t8_cmesh_examples.h (hunk 5 above)
Comment (Davknapp) [reply src/t8_cmesh/t8_cmesh_examples.h:111]: It does now!

**Review by sandro-elsweijer — APPROVED** [review]

**Review by sandro-elsweijer — DISMISSED** [review]

**Review by sandro-elsweijer — APPROVED** [review]
