### PR TITLE
Documentation: Fix doxygen errors. 

### LINKED ISSUE #1754: fix t8_vtk documentation
# Bug report
Fix all doxygen errors related to files in the t8_vtk folder
**Describe the bug**
A clear and concise description of what the bug/unexpected behaviour is.

**To Reproduce**
Which command did you run/which function did you call?

**Expected behavior**

**Log files**
- If possible, add any output and error messages that you got
- Please upload the `config.log` file (when building with autotools)
- For failing tests, please upload the `test-suite.log` file (when building with autotools)
- When building with CMake please upload
  - `CMakeCache.txt`
  - `CMakeFiles/CMakeError.log`
  - `CMakeFiles/CMakeOutput.log`
  - `Testing/Temporary/FailedTest.log` (for failing tests)
  - `Testing/Temporary/LastTestsFailed.log` (for failing tests)

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04, Windows 11]
 - Compiler: [e.g., gcc, icc, mpicc]
 - Compiler version: [e.g. the output of 'gcc --version']
 - MPI version (if MPI is used): [The output of 'mpirun --version' or 'mpiexec --version']
 
**Estimated priority**
Which of these is most applicable (remove the others):

"Priority: high"  Should be solved as soon as possible 

"Priority: medium"  Should be solved within half a year 

"Priority: low" Should be solved eventually

**Additional context**

### PR DESCRIPTION
**Pull request by Davknapp**
Closes #1754 

Fixed all doxygen errors related to src/t8_vtk/* 

**_All these boxes must be checked by the AUTHOR before requesting review:_**
- [x] The PR is *small enough* to be reviewed easily. If not, consider splitting up the changes in multiple PRs.
- [x] The title starts with one of the following prefixes: `Documentation:`, `Bugfix:`, `Feature:`, `Improvement:` or `Other:`.
- [x] If the PR is related to an issue, make sure to link it.
- [x] The author made sure that, as a reviewer, he/she would check all boxes below.

**_All these boxes must be checked by the REVIEWERS before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is *fully understood, bug free, well-documented and well-structured*.
#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually.
- [ ] The code follows the [t8code coding guidelines](https://github.com/DLR-AMR/t8code/wiki/Coding-Guideline).
- [ ] New source/header files are properly added to the CMake files.
- [ ] The code is well documented. In particular, all function declarations, structs/classes and their members have a proper doxygen documentation.
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue).
#### Tests
- [ ] The code is covered in an existing or new test case using Google Test.
- [ ] The code coverage of the project (reported in the CI) should not decrease. If coverage is decreased, make sure that this is reasonable and acceptable.
- [ ] Valgrind doesn't find any bugs in the new code. [This script](https://github.com/DLR-AMR/t8code/blob/main/scripts/check_valgrind.sh) can be used to check for errors; see also this [wiki article](https://github.com/DLR-AMR/t8code/wiki/Debugging-with-valgrind).

If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually).
#### Scripts and Wiki
- [ ] If a new directory with source files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example or tutorial and a Wiki article.
#### License
- [x] The author added a BSD statement to `doc/` (or already has one).

### CODE REVIEW

File: src/t8_vtk/t8_vtk_writer.cxx [hunk 1]
```diff
@@ -98,6 +101,9 @@ vtk_writer<t8_forest_t>::write_ASCII (const t8_forest_t forest)
                                     this->data);
 }
 
+/**
+ * \brief Write a cmesh to a VTK file in ASCII format.
```
Comment (sandro-elsweijer) [inline src/t8_vtk/t8_vtk_writer.cxx]:
```suggestion
 * Write a cmesh to a VTK file in ASCII format.
```

File: src/t8_vtk/t8_vtk_writer_helper.hxx [hunk 2]
```diff
@@ -20,12 +20,19 @@
...
+ * This file contains helper functions for the vtk writer.
+ */
+
 #ifndef T8_VTK_WRITER_HELPER
 #define T8_VTK_WRITER_HELPER
 
 #include <t8.h>
 #include <t8_forest/t8_forest.h>
 
+/** The maximal number of corners for a quadratic vtk element */
```
Comment (sandro-elsweijer) [inline src/t8_vtk/t8_vtk_writer_helper.hxx]:
```suggestion
/** The maximum number of corners for a quadratic vtk element */
```

File: src/t8_vtk/t8_vtk_writer_helper.hxx [hunk 3]
```diff
@@ -120,7 +127,7 @@ grid_local_num_elements (const grid_t grid);
  * 
  * \tparam grid_t Either a cmesh or a forest.
  * \param[in] grid The forest/cmesh to use.
- * \param[in, out] Bounds defined by xmin, xmax, ymin, ymax, zmin, zmax.
+ * \param[in, out] bounds defined by xmin, xmax, ymin, ymax, zmin, zmax.
```
Comment (sandro-elsweijer) [inline src/t8_vtk/t8_vtk_writer_helper.hxx:130]: We often capitalize the first word

File: src/t8_vtk/t8_with_vtk/t8_vtk_parallel.hxx [hunk 4]
```diff
@@ -47,8 +48,9 @@ t8_read_parallel_unstructured (const char *filename, vtkSmartPointer<vtkDataSet>
  * 
  * \param[in] filename  The name of a parallel vtk file to a distributed vtkPolyData
  * \param[in] grid On input a vtkSmartPointer, that will hold the grid described
- *                 by the pieces read on this proc. 
- * \returns        non-zero on success, zero if the reading failed. 
+ *                 by the pieces read on this proc.
+ * \param[in] comm The MPI communicator to use for reading the file.
+ * \returns        non-zero on success, zero if the reading failed.
```
Comment (sandro-elsweijer) [inline src/t8_vtk/t8_with_vtk/t8_vtk_parallel.hxx]:
```suggestion
 * \returns        read_success on success, read_failure if the reading failed.
```

File: src/t8_vtk/t8_vtk_writer.cxx [hunk 5]
```diff
@@ -89,6 +89,9 @@ vtk_writer<t8_cmesh_t>::t8_grid_tree_to_vtk_cells (
 }
 #endif /* T8_ENABLE_VTK */
 
+/**
+ * \brief Write a forest to a VTK file in ASCII format.
```
Comment (sandro-elsweijer) [inline src/t8_vtk/t8_vtk_writer.cxx]:
```suggestion
 * Write a forest to a VTK file in ASCII format.
```
Do you maybe want to re-configure your macro so that it omits the `\brief`?

File: src/t8_vtk/t8_vtk_writer_helper.hxx (hunk 3 above)
Comment (Davknapp) [reply src/t8_vtk/t8_vtk_writer_helper.hxx:130]: yes, but the variable starts with a small letter.

**Review by sandro-elsweijer — APPROVED** [review]
