### PR TITLE
Fix Bug 873

### LINKED ISSUE #873: Bug in Coarsen and Refine
Hi Team,

We've discovered a bug when coarsening and refining a mesh (using a gmsh file), where element coordinates are broken when executing in parallel. This causes elements to 'disappear', as seen in the animation below. I've added the modified step3 program and the gmsh file (save as box_mesh.msh) below.  

Thanks, Andrew  

---

Here is an example using a modified version of the step3 program (source code below):
__Single Core__ (expected behavior): `mpirun -np 1 ./t8_step3_adapt_forest`  
t8code_adapt_1rank

__Multi Core__ (broken): `mpirun -np 4 ./t8_step3_adapt_forest`  
t8code_adapt_4rank

__GMSH File__ (save as `box_mesh.msh`):  
```
$MeshFormat
2.2 0 8
$EndMeshFormat
$Nodes
44
1 0.0000000000000000E+00 0.0000000000000000E+00 0.0000000000000000E+00
2 0.1000000000000000E+01 0.0000000000000000E+00 0.0000000000000000E+00
3 0.2000000000000000E+01 0.0000000000000000E+00 0.0000000000000000E+00
4 0.3000000000000000E+01 0.0000000000000000E+00 0.0000000000000000E+00
5 0.4000000000000000E+01 0.0000000000000000E+00 0.0000000000000000E+00
6 0.5000000000000000E+01 0.0000000000000000E+00 0.0000000000000000E+00
7 0.6000000000000000E+01 0.0000000000000000E+00 0.0000000000000000E+00
8 0.7000000000000000E+01 0.0000000000000000E+00 0.0000000000000000E+00
9 0.8000000000000000E+01 0.0000000000000000E+00 0.0000000000000000E+00
10 0.9000000000000000E+01 0.0000000000000000E+00 0.0000000000000000E+00
11 0.1000000000000000E+02 0.0000000000000000E+00 0.0000000000000000E+00
12 0.0000000000000000E+00 0.1000000000000000E+01 0.0000000000000000E+00
13 0.1000000000000000E+01 0.1000000000000000E+01 0.0000000000000000E+00
14 0.2000000000000000E+01 0.1000000000000000E+01 0.0000000000000000E+00
15 0.3000000000000000E+01 0.1000000000000000E+01 0.0000000000000000E+00
16 0.4000000000000000E+01 0.1000000000000000E+01 0.0000000000000000E+00
17 0.5000000000000000E+01 0.1000000000000000E+01 0.0000000000000000E+00
18 0.6000000000000000E+01 0.1000000000000000E+01 0.0000000000000000E+00
19 0.7000000000000000E+01 0.1000000000000000E+01 0.0000000000000000E+00
20 0.8000000000000000E+01 0.1000000000000000E+01 0.0000000000000000E+00
21 0.9000000000000000E+01 0.1000000000000000E+01 0.0000000000000000E+00
22 0.1000000000000000E+02 0.1000000000000000E+01 0.0000000000000000E+00
23 0.0000000000000000E+00 0.0000000000000000E+00 0.1000000000000000E+01
24 0.1000000000000000E+01 0.0000000000000000E+00 0.1000000000000000E+01
25 0.2000000000000000E+01 0.0000000000000000E+00 0.1000000000000000E+01
26 0.3000000000000000E+01 0.0000000000000000E+00 0.1000000000000000E+01
27 0.4000000000000000E+01 0.0000000000000000E+00 0.1000000000000000E+01
28 0.5000000000000000E+01 0.0000000000000000E+00 0.1000000000000000E+01
29 0.6000000000000000E+01 0.0000000000000000E+00 0.1000000000000000E+01
30 0.7000000000000000E+01 0.0000000000000000E+00 0.1000000000000000E+01
31 0.8000000000000000E+01 0.0000000000000000E+00 0.1000000000000000E+01
32 0.9000000000000000E+01 0.0000000000000000E+00 0.1000000000000000E+01
33 0.1000000000000000E+02 0.0000000000000000E+00 0.1000000000000000E+01
34 0.0000000000000000E+00 0.1000000000000000E+01 0.1000000000000000E+01
35 0.1000000000000000E+01 0.1000000000000000E+01 0.1000000000000000E+01
36 0.2000000000000000E+01 0.1000000000000000E+01 0.1000000000000000E+01
37 0.3000000000000000E+01 0.1000000000000000E+01 0.1000000000000000E+01
38 0.4000000000000000E+01 0.1000000000000000E+01 0.1000000000000000E+01
39 0.5000000000000000E+01 0.1000000000000000E+01 0.1000000000000000E+01
40 0.6000000000000000E+01 0.1000000000000000E+01 0.1000000000000000E+01
41 0.7000000000000000E+01 0.1000000000000000E+01 0.1000000000000000E+01
42 0.8000000000000000E+01 0.1000000000000000E+01 0.1000000000000000E+01
43 0.9000000000000000E+01 0.1000000000000000E+01 0.1000000000000000E+01
44 0.1000000000000000E+02 0.1000000000000000E+01 0.1000000000000000E+01
$EndNodes
$Elements
52
1 3 2   4  4 12 13 35 34
2 3 2   4  4 13 14 36 35
3 3 2   4  4 14 15 37 36
4 3 2   4  4 15 16 38 37
5 3 2   4  4 16 17 39 38
6 3 2   4  4 17 18 40 39
7 3 2   4  4 18 19 41 40
8 3 2   4  4 19 20 42 41
9 3 2   4  4 20 21 43 42
10 3 2   4  4 21 22 44 43
11 3 2   3  3 1 23 24 2
12 3 2   3  3 2 24 25 3
13 3 2   3  3 3 25 26 4
14 3 2   3  3 4 26 27 5
15 3 2   3  3 5 27 28 6
16 3 2   3  3 6 28 29 7
17 3 2   3  3 7 29 30 8
18 3 2   3  3 8 30 31 9
19 3 2   3  3 9 31 32 10
20 3 2   3  3 10 32 33 11
21 3 2   5  5 1 2 13 12
22 3 2   5  5 2 3 14 13
23 3 2   5  5 3 4 15 14
24 3 2   5  5 4 5 16 15
25 3 2   5  5 5 6 17 16
26 3 2   5  5 6 7 18 17
27 3 2   5  5 7 8 19 18
28 3 2   5  5 8 9 20 19
29 3 2   5  5 9 10 21 20
30 3 2   5  5 10 11 22 21
31 3 2   2  2 11 33 44 22
32 3 2   1  1 1 12 34 23
33 3 2   6  6 23 34 35 24
34 3 2   6  6 24 35 36 25
35 3 2   6  6 25 36 37 26
36 3 2   6  6 26 37 38 27
37 3 2   6  6 27 38 39 28
38 3 2   6  6 28 39 40 29
39 3 2   6  6 29 40 41 30
40 3 2   6  6 30 41 42 31
41 3 2   6  6 31 42 43 32
42 3 2   6  6 32 43 44 33
43 5 2 7 7 1 2 13 12 23 24 35 34
44 5 2 7 7 2 3 14 13 24 25 36 35
45 5 2 7 7 3 4 15 14 25 26 37 36
46 5 2 7 7 4 5 16 15 26 27 38 37
47 5 2 7 7 5 6 17 16 27 28 39 38
48 5 2 7 7 6 7 18 17 28 29 40 39
49 5 2 7 7 7 8 19 18 29 30 41 40
50 5 2 7 7 8 9 20 19 30 31 42 41
51 5 2 7 7 9 10 21 20 31 32 43 42
52 5 2 7 7 10 11 22 21 32 33 44 43
$EndElements
$PhysicalNames
7
2 1 "FACE-1"
2 2 "FACE-2"
2 3 "FACE-3"
2 4 "FACE-4"
2 5 "FACE-5"
2 6 "FACE-6"
2 7 "VOL1"
$EndPhysicalNames
```

__Modified Step3 Source Code__:  
```C++
/*
  This file is part of t8code.
  t8code is a C library to manage a collection (a forest) of multiple
  connected adaptive space-trees of general element types in parallel.

  Copyright (C) 2015 the developers

  t8code is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  t8code is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with t8code; if not, write to the Free Software Foundation, Inc.,
  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
*/

/* This is step3 of the t8code tutorials.
 * After generating a coarse mesh (step1) and building a uniform forest
 * on it (step2), we will now adapt (= refine and coarsen) the forest
 * according to our own criterion.
 *
 * The geometry (coarse mesh) is again a cube, this time modelled with
 * 6 tetrahedra, 6 prisms and 4 cubes.
 * We refine an element if its midpoint is within a sphere of given radius
 * around the point (0.5, 0.5, 1) and we coarsen outside of a given radius.
 * We will use non-recursive refinement, that means that the refinement level
 * of any element will change by at most +-1.
 *
 * How you can experiment here:
 *   - Look at the paraview output files of the unifomr and the adapted forest.
 *     For the adapted forest you can apply a slice filter to look into the cube.
 *   - Run the program with different process numbers. You should see that refining is
 *     independent of the number of processes, but coarsening is not.
 *     This is due to the face that a family can only be coarsened if it is completely
 *     local to a single process and the distribution among the process may break this property.
 *   - Change the midpoint coordinates and the radii.
 *   - Change the adaptation criterion such that elements inside the sphere are coarsened
 *     and elements outside are refined.
 *   - Use t8_productionf to print the local number of elements on each process.
 *     Notice, that the uniform forest is evenly distributed, but that the adapted forest
 *     is not. This is due to the fact that we do not repartition our forest here.
 *   - Add a maximum refinement level to the adapt_data struct and use non-recursive refinement.
 *     Do not refine an element if it has reached the maximum level. (Hint: ts->t8_element_level)
 */

#include <t8.h>                                     /* General t8code header, always include this. */
#include <t8_cmesh.h>                               /* cmesh definition and basic interface. */
#include <t8_cmesh/t8_cmesh_examples.h>             /* A collection of exemplary cmeshes */
#include <t8_forest/t8_forest_general.h>            /* forest definition and basic interface. */
#include <t8_forest/t8_forest_io.h>                 /* save forest */
#include <t8_forest/t8_forest_geometrical.h>        /* geometrical information of the forest */
#include <t8_schemes/t8_default/t8_default_cxx.hxx> /* default refinement scheme. */
#include <t8_vec.h>                                 /* Basic operations on 3D vectors. */
#include <tutorials/general/t8_step3.h>
#include <t8_cmesh_readmshfile.h>
#include <t8_cmesh/t8_cmesh_trees.h>

T8_EXTERN_C_BEGIN ();

double glob_mid, glob_r;

/* The adaptation callback function. This function will be called once for each element
 * and the return value decides whether this element should be refined or not.
 *   return > 0 -> This element should get refined.
 *   return = 0 -> This element should not get refined.
 * If the current element is the first element of a family (= all level l elements that arise from refining
 * the same level l-1 element) then this function is called with the whole family of elements
 * as input and the return value additionally decides whether the whole family should get coarsened.
 *   return > 0 -> The first element should get refined.
 *   return = 0 -> The first element should not get refined.
 *   return < 0 -> The whole family should get coarsened.
 *
 * \param [in] forest       The current forest that is in construction.
 * \param [in] forest_from  The forest from which we adapt the current forest (in our case, the uniform forest)
 * \param [in] which_tree   The process local id of the current tree.
 * \param [in] lelement_id  The tree local index of the current element (or the first of the family).
 * \param [in] ts           The refinement scheme for this tree's element class.
 * \param [in] is_family    if 1, the first \a num_elements entries in \a elements form a family. If 0, they do not.
 * \param [in] num_elements The number of entries in \a elements elements that are defined.
 * \param [in] elements     The element or family of elements to consider for refinement/coarsening.
 */
int
t8_step3_adapt_callback (t8_forest_t forest, t8_forest_t forest_from, t8_locidx_t which_tree, t8_locidx_t lelement_id,
                         t8_eclass_scheme_c *ts, const int is_family, const int num_elements, t8_element_t *elements[])
{
  /* Our adaptation criterion is to look at the midpoint coordinates of the current element and if
   * they are inside a sphere around a given midpoint we refine, if they are outside, we coarsen. */
  double centroid[3]; /* Will hold the element midpoint. */
  /* In t8_step3_adapt_forest we pass a t8_step3_adapt_data pointer as user data to the
   * t8_forest_new_adapt function. This pointer is stored as the used data of the new forest
   * and we can now access it with t8_forest_get_user_data (forest). */
  const struct t8_step3_adapt_data *adapt_data = (const struct t8_step3_adapt_data *) t8_forest_get_user_data (forest);
  double dist; /* Will store the distance of the element's midpoint and the sphere midpoint. */

  /* You can use T8_ASSERT for assertions that are active in debug mode (when configured with --enable-debug).
   * If the condition is not true, then the code will abort.
   * In this case, we want to make sure that we actually did set a user pointer to forest and thus
   * did not get the NULL pointer from t8_forest_get_user_data.
   */
  T8_ASSERT (adapt_data != NULL);

  /* Compute the element's centroid coordinates. */
  t8_forest_element_centroid (forest_from, which_tree, elements[0], centroid);

  /* Compute the distance to our sphere midpoint. */
  dist = t8_vec_dist (centroid, adapt_data->midpoint);
  if (dist < adapt_data->refine_if_inside_radius) {
    /* Refine this element. */
    return 1;
  }
  else if (is_family && dist > adapt_data->coarsen_if_outside_radius) {
    /* Coarsen this family. Note that we check for is_family before, since returning < 0
     * if we do not have a family as input is illegal. */
    return -1;
  }
  /* Do not change this element. */
  return 0;
}

int
t8_adapt_callback_testA (t8_forest_t forest, t8_forest_t forest_from, t8_locidx_t which_tree, t8_locidx_t lelement_id,
                         t8_eclass_scheme_c *ts, const int is_family, const int num_elements, t8_element_t *elements[])
{
  /* Our adaptation criterion is to look at the midpoint coordinates of the current element and if
   * they are inside a sphere around a given midpoint we refine, if they are outside, we coarsen. */
  int level_min = 0;
  int level_max = 3;

  int level = ts->t8_element_level(elements[0]);
  double centroid[3]; /* Will hold the element midpoint. */

  /* Compute the element's centroid coordinates. */
  t8_forest_element_centroid (forest_from, which_tree, elements[0], centroid);

  double mid, r;
  mid = glob_mid;
  r   = glob_r;

  int itag;
  itag = 0;
  if(centroid[0] <  mid+r && centroid[0] >  mid-r){
    itag = 1;
  } else
  if(centroid[0] <  mid-r && is_family){
    itag = -1;
  }
  if(level >= level_max && itag == 1) itag = 0;
  if(level <= level_min && itag == -1) itag = 0;

  return itag;
}

/* Adapt a forest according to our t8_step3_adapt_callback function.
 * This will create a new forest and return it. */
t8_forest_t
t8_step3_adapt_forest (t8_forest_t forest)
{
  t8_forest_t forest_adapt;
  struct t8_step3_adapt_data adapt_data = {
    { 0.5, 0.5, 1 }, /* Midpoints of the sphere. */
    0.2,             /* Refine if inside this radius. */
    0.4              /* Coarsen if outside this radius. */
  };

  /* Check that forest is a committed, that is valid and usable, forest. */
  T8_ASSERT (t8_forest_is_committed (forest));

  /* Create a new forest that is adapted from \a forest with our adaptation callback.
   * We provide the adapt_data as user data that is stored as the used_data pointer of the
   * new forest (see also t8_forest_set_user_data).
   * The 0, 0 arguments are flags that control
   *   recursive  -    If non-zero adaptation is recursive, thus if an element is adapted the children
   *                   or parents are plugged into the callback again recursively until the forest does not
   *                   change any more. If you use this you should ensure that refinement will stop eventually.
   *                   One way is to check the element's level against a given maximum level.
   *   do_face_ghost - If non-zero additionally a layer of ghost elements is created for the forest.
   *                   We will discuss ghost in later steps of the tutorial.
   */
  forest_adapt = t8_forest_new_adapt (forest, t8_step3_adapt_callback, 0, 0, &adapt_data);

  return forest_adapt;
}

t8_forest_t
t8_adapt_forest_test (t8_forest_t forest)
{
  t8_forest_t balanced_forest;

  /* Check that forest is a committed, that is valid and usable, forest. */
  T8_ASSERT (t8_forest_is_committed (forest));

  /* Create a new forest that is adapted from \a forest with our adaptation callback.
   * We provide the adapt_data as user data that is stored as the used_data pointer of the
   * new forest (see also t8_forest_set_user_data).
   * The 0, 0 arguments are flags that control
   *   recursive  -    If non-zero adaptation is recursive, thus if an element is adapted the children
   *                   or parents are plugged into the callback again recursively until the forest does not
   *                   change any more. If you use this you should ensure that refinement will stop eventually.
   *                   One way is to check the element's level against a given maximum level.
   *   do_face_ghost - If non-zero additionally a layer of ghost elements is created for the forest.
   *                   We will discuss ghost in later steps of the tutorial.
   */

  t8_forest_ref(forest);
  t8_forest_init(&balanced_forest);
  t8_forest_set_adapt(balanced_forest, forest, t8_adapt_callback_testA, 0);
  t8_forest_set_balance(balanced_forest, forest, 1);
  t8_forest_set_ghost(balanced_forest, 1, T8_GHOST_FACES);
  t8_forest_commit(balanced_forest);

  t8_forest_unref(&forest);
  return balanced_forest;
}

/* Print the local and global number of elements of a forest. */
void
t8_step3_print_forest_information (t8_forest_t forest)
{
  t8_locidx_t local_num_elements;
  t8_gloidx_t global_num_elements;

  /* Check that forest is a committed, that is valid and usable, forest. */
  T8_ASSERT (t8_forest_is_committed (forest));

  /* Get the local number of elements. */
  local_num_elements = t8_forest_get_local_num_elements (forest);
  /* Get the global number of elements. */
  global_num_elements = t8_forest_get_global_num_elements (forest);
  t8_global_productionf (" [step3] Local number of elements:\t\t%i\n", local_num_elements);
  t8_global_productionf (" [step3] Global number of elements:\t%li\n", global_num_elements);
}

static t8_forest_t
t8_step3_partition_ghost (t8_forest_t forest)
{
  t8_forest_t new_forest;

  /* Check that forest is a committed, that is valid and usable, forest. */
  T8_ASSERT (t8_forest_is_committed (forest));

  /* Initialize */
  t8_forest_init (&new_forest);

  /* Tell the new_forest that is should partition the existing forest.
   * This will change the distribution of the forest elements among the processes
   * in such a way that afterwards each process has the same number of elements
   * (+- 1 if the number of elements is not divisible by the number of processes).
   *
   * The third 0 argument is the flag 'partition_for_coarsening' which is currently not
   * implemented. Once it is, this will ensure that a family of elements will not be split
   * across multiple processes and thus one level coarsening is always possible (see also the
   * comments on coarsening in t8_step3).
   */
  t8_forest_set_partition (new_forest, forest, 0);
  /* Tell the new_forest to create a ghost layer.
   * This will gather those face neighbor elements of process local element that reside
   * on a different process.
   *
   * We currently support ghost mode T8_GHOST_FACES that creates face neighbor ghost elements
   * and will in future also support other modes for edge/vertex neighbor ghost elements.
   */
  t8_forest_set_ghost (new_forest, 1, T8_GHOST_FACES);
  /* Commit the forest, this step will perform the partitioning and ghost layer creation. */
  t8_forest_commit (new_forest);

  return new_forest;
}

int
t8_step3_main (int argc, char **argv)
{
  int mpiret;
  sc_MPI_Comm comm;
  t8_cmesh_t cmesh;
  t8_forest_t forest;

  /* The uniform refinement level of the forest. */
  const int level = 3;

  /* Initialize MPI. This has to happen before we initialize sc or t8code. */
  mpiret = sc_MPI_Init (&argc, &argv);

  /* Error check the MPI return value. */
  SC_CHECK_MPI (mpiret);

  /* Initialize the sc library, has to happen before we initialize t8code. */
  sc_init (sc_MPI_COMM_WORLD, 1, 1, NULL, SC_LP_ESSENTIAL);
  /* Initialize t8code with log level SC_LP_PRODUCTION. See sc.h for more info on the log levels. */
  t8_init (SC_LP_PRODUCTION);

  /* Print a message on the root process. */
  t8_global_productionf (" [step3] \n");
  t8_global_productionf (" [step3] Hello, this is the step3 example of t8code.\n");
  t8_global_productionf (" [step3] In this example we will refine and coarsen a forest.\n");
  t8_global_productionf (" [step3] \n");

  /* We will use MPI_COMM_WORLD as a communicator. */
  comm = sc_MPI_COMM_WORLD;

  /*
   * Setup.
   * Build cmesh and uniform forest.
   */
  char *mshfile;
  if(argc == 2) {
    mshfile = argv[1];
  }
  else{
    mshfile = "box_mesh";
  }

  t8_productionf(" argc:%i %s\n",argc,mshfile);
  cmesh = t8_cmesh_from_msh_file (mshfile, 1, sc_MPI_COMM_WORLD, 3, 0, 0);
  if(t8_cmesh_trees_is_face_consistent (cmesh, cmesh->trees)){
      t8_productionf(" pass consistent test\n");
  }
  else{
      t8_productionf(" failed consistent test************************\n");
  }
  t8_cmesh_t cmesh_partition;
  t8_cmesh_init(&cmesh_partition);
  t8_cmesh_set_partition_uniform(cmesh_partition,0,t8_scheme_new_default_cxx());
  t8_cmesh_set_derive(cmesh_partition,cmesh);
  t8_cmesh_commit(cmesh_partition,comm);
  forest = t8_forest_new_uniform (cmesh_partition, t8_scheme_new_default_cxx (), 0, 1, comm);

  /* Write forest to vtu files. */
  const char *prefix_adapt0 = "adapt0";
  t8_forest_write_vtk (forest, prefix_adapt0);
  t8_global_productionf (" [step3] Wrote uniform forest to vtu files: %s*\n", prefix_adapt0);

  /*
   *  Adapt the forest.
   */
  glob_mid = 2;
  glob_r   = 2;
  forest = t8_adapt_forest_test (forest);
  forest = t8_step3_partition_ghost (forest);
  const char *prefix_adapt1 = "adapt1";
  t8_forest_write_vtk (forest, prefix_adapt1);

  glob_mid = 3;
  forest = t8_adapt_forest_test (forest);
  forest = t8_step3_partition_ghost (forest);
  const char *prefix_adapt2 = "adapt2";
  t8_forest_write_vtk (forest, prefix_adapt2);

  glob_mid = 4;
  forest = t8_adapt_forest_test (forest);
  forest = t8_step3_partition_ghost (forest);
  const char *prefix_adapt3 = "adapt3";
  t8_forest_write_vtk (forest, prefix_adapt3);

  glob_mid = 5;
  forest = t8_adapt_forest_test (forest);
  forest = t8_step3_partition_ghost (forest);
  const char *prefix_adapt4 = "adapt4";
  t8_forest_write_vtk (forest, prefix_adapt4);

  glob_mid = 6;
  forest = t8_adapt_forest_test (forest);
  forest = t8_step3_partition_ghost (forest);
  const char *prefix_adapt5 = "adapt5";
  t8_forest_write_vtk (forest, prefix_adapt5);

  // glob_mid = 7;
  // forest = t8_adapt_forest_test (forest);
  // forest = t8_step3_partition_ghost (forest);
  // const char *prefix_adapt6 = "adapt6";
  // t8_forest_write_vtk (forest, prefix_adapt6);

  /* Destroy the forest. */
  t8_forest_unref (&forest);
  t8_global_productionf (" [step3] Destroyed forest.\n");

  sc_finalize ();

  mpiret = sc_MPI_Finalize ();
  SC_CHECK_MPI (mpiret);

  return 0;
}

T8_EXTERN_C_END ();
```

### PR DESCRIPTION
**Pull request by Davknapp**
Cause of the error: 
During partitioning of the cmesh vertex-data of the tree can be moved around. If the active tree of the geometry is the same as befor partitioning the vertex-data has been moved without notifying the geometry. 
Solution:
The active tree of the geometry-handler is set to a negative value that is out of bounds of the possible ltreeids. Therefore the active tree is set again as soon as we want to load tree data and the tree-data is actually loaded. 

Thanks to @lukasdreyer for helping with the bug-hunt.

Closes #873 

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### Licence

- [ ] The author added a BSD statement to `doc/` (or already has one)

### CODE REVIEW

File: src/t8_cmesh/t8_cmesh_partition.c [hunk 1]
```diff
@@ -1596,6 +1596,10 @@ t8_cmesh_partition (t8_cmesh_t cmesh, sc_MPI_Comm comm)
     /* Runtime = current_time - start_time */
     cmesh->profile->partition_runtime = sc_MPI_Wtime () - cmesh->profile->partition_runtime;
   }
+  /* Deactivate the active tree. Tree related data (such as vertices) might have been moved by the new partition and 
+   * has to be loaded again if needed. */
+  cmesh->geometry_handler->active_tree = -cmesh->num_local_trees - 1;
+
```
Comment (holke) [inline src/t8_cmesh/t8_cmesh_partition.c:1602]: Lets move this code up before the time measurement.
Any computation should happen inside the timing.

Lets add a new function to the geometry handler "set_active_tree_invaid".
That we, cmesh_partition does not need to know the implementation detail and also the number does not seem so magical here.

**Review by holke — CHANGES_REQUESTED** [review]

File: src/t8_cmesh/t8_cmesh_partition.c (hunk 1 above)
Comment (Davknapp) [reply src/t8_cmesh/t8_cmesh_partition.c:1602]: Done

File: src/t8_geometry/t8_geometry.h [hunk 2]
```diff
@@ -146,6 +146,15 @@ t8_geom_handler_get_num_geometries (const t8_geometry_handler_t *geom_handler);
 const t8_geometry_c *
 t8_geom_handler_get_unique_geometry (const t8_geometry_handler_t *geom_handler);
 
+/**
+ * Deactivate the current active tree. Can be used to reload data, after it has been moved, for example by the
+ * partition-algorithm
+ * 
+ * \param[in,out] geom_handler The geometry handler, where the tree has to be deactivated.
```
Comment (holke) [inline src/t8_geometry/t8_geometry.h:153]:
```suggestion
 * \param[in,out] geom_handler The geometry handler, where the tree has to be deactivated.
 * \note \a geom_handler must be committed before calling this function.
```

**Review by holke — APPROVED** [review]
