### PR TITLE
Documentation: Fix doxygen errors in src

### LINKED ISSUE #1755: Fix src documentation
# Bug report
Fix all doxygen errors for all files in the src-folder
**Describe the bug**
A clear and concise description of what the bug/unexpected behaviour is.

**To Reproduce**
Which command did you run/which function did you call?

**Expected behavior**

**Log files**
- If possible, add any output and error messages that you got
- Please upload the `config.log` file (when building with autotools)
- For failing tests, please upload the `test-suite.log` file (when building with autotools)
- When building with CMake please upload
  - `CMakeCache.txt`
  - `CMakeFiles/CMakeError.log`
  - `CMakeFiles/CMakeOutput.log`
  - `Testing/Temporary/FailedTest.log` (for failing tests)
  - `Testing/Temporary/LastTestsFailed.log` (for failing tests)

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04, Windows 11]
 - Compiler: [e.g., gcc, icc, mpicc]
 - Compiler version: [e.g. the output of 'gcc --version']
 - MPI version (if MPI is used): [The output of 'mpirun --version' or 'mpiexec --version']
 
**Estimated priority**
Which of these is most applicable (remove the others):

"Priority: high"  Should be solved as soon as possible 

"Priority: medium"  Should be solved within half a year 

"Priority: low" Should be solved eventually

**Additional context**

### PR DESCRIPTION
**Pull request by lukasdreyer**
**_Describe your changes here:_**
closes #1755

**_All these boxes must be checked by the AUTHOR before requesting review:_**
- [x] The PR is *small enough* to be reviewed easily. If not, consider splitting up the changes in multiple PRs.
- [x] The title starts with one of the following prefixes: `Documentation:`, `Bugfix:`, `Feature:`, `Improvement:` or `Other:`.
- [x] If the PR is related to an issue, make sure to link it.
- [x] The author made sure that, as a reviewer, he/she would check all boxes below.

**_All these boxes must be checked by the REVIEWERS before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is *fully understood, bug free, well-documented and well-structured*.
#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually.
- [ ] The code follows the [t8code coding guidelines](https://github.com/DLR-AMR/t8code/wiki/Coding-Guideline).
- [ ] New source/header files are properly added to the CMake files.
- [ ] The code is well documented. In particular, all function declarations, structs/classes and their members have a proper doxygen documentation.
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue).
#### Tests
- [ ] The code is covered in an existing or new test case using Google Test.
- [ ] The code coverage of the project (reported in the CI) should not decrease. If coverage is decreased, make sure that this is reasonable and acceptable.
- [ ] Valgrind doesn't find any bugs in the new code. [This script](https://github.com/DLR-AMR/t8code/blob/main/scripts/check_valgrind.sh) can be used to check for errors; see also this [wiki article](https://github.com/DLR-AMR/t8code/wiki/Debugging-with-valgrind).

If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually).
#### Scripts and Wiki
- [ ] If a new directory with source files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example or tutorial and a Wiki article.
#### License
- [ ] The author added a BSD statement to `doc/` (or already has one).

### CODE REVIEW

File: src/t8_netcdf.h [hunk 1]
```diff
@@ -47,14 +47,20 @@ typedef enum t8_netcdf_variable_type {
...
 {
+  /** short name of the variable*/
   const char *variable_name;
+  /** long name of the variable*/
   const char *variable_long_name;
+  /** unit of the variable*/
   const char *variable_units;
+  /** datatype of the variable*/
   t8_netcdf_variable_type_t datatype;
+  /** Dimension id of the user??? TODO!!*/
```
Comment (lukasdreyer) [inline src/t8_netcdf.h]: @Niklas997: could you please clarify the meaning of this variable?

**Review by Davknapp — COMMENTED** [review]
Looks good so far, we only need to wait for a reaction from @Niklas997

File: src/t8_netcdf.h (hunk 1 above)
Comment (Niklas997) [inline src/t8_netcdf.h]:
```suggestion
  /** The unique identifier netCDF assigns to this variable once it is defined in the file*/
```
This member's name is poorly chosen, I need to admit. The name is misleading since the purpose of this member variable is to store the unique ID netCDF will assign to this variable once it has been defined in the netCDF file. This ID is needed in order to address the variable when for example the data is written to it. A suitable name would be something like "variable_id".  I do not know why this name has been chosen initially, I am sorry.

**Review by Davknapp — APPROVED** [review]

**Review by Davknapp — APPROVED** [review]
