### PR TITLE
Fix issue 352

### LINKED ISSUE #352: `t8_cmesh_set_partition_uniform` does not work when geometry is committed only on the master rank
The example `example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole` crashes in parallel, and it seems to have something to do with the partitioning of geometries. If the cmesh is build by a main rank and the geometry is also only committed on the main rank, the geometry of the trees is not found by the other processes after calling `t8_cmesh_set_partition_uniform`.

### PR DESCRIPTION
**Pull request by holke**
**_Describe your changes here:_**

Fixes #352
The ./t8_load_and_refine_square_w_hole example did not work in parallel since the geometries were not registered in parallel in the cmesh msh file reader.
Fixed it by registering the geometries on every rank.

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

- [x] The author added a BSD statement to `doc/` (or already has one)
- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)
- [x] New source/header files are properly added to the Makefiles
- [x] New Datatypes are added to t8indent_custom_datatypes.txt
- [ ] The reviewer executed the new code features at least once and checked the results manually
- [x] The code is covered in an existing or new test case
- [x] New tests use the Google Test framework
- [x] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [x] The code is well documented
- [x] All function declarations, structs/classes and their members have a proper doxygen documentation
- [x] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)
- [x] Testing of this template: If you feel something is missing from this list, contact the developers

### CODE REVIEW

File: src/t8_cmesh/t8_cmesh_readmshfile.cxx [hunk 1]
```diff
@@ -954,9 +955,12 @@ t8_cmesh_msh_file_4_read_eles (t8_cmesh_t cmesh, FILE *fp,
         /* *INDENT-OFF* */
 
         /* Calculate the parametric geometries of the tree */
-        if (occ_geometry != NULL)
+        if (use_occ_geometry)
         {
 #if T8_WITH_OCC
+          const t8_geometry_c *occ_geometry_base = t8_cmesh_get_tree_geometry (cmesh, tree_count);
```
Comment (sandro-elsweijer) [inline src/t8_cmesh/t8_cmesh_readmshfile.cxx:961]: When running the naca tutorial in debug mode, I get an assertion here: `Abort: Assertion 't8_cmesh_is_committed (cmesh)'`.
Moreover, the generated forests from the release build are deformed. This may be connected somehow.
grafik

**Review by sandro-elsweijer — CHANGES_REQUESTED** [review]
I found some bugs 😇

File: src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.h [hunk 2]
```diff
@@ -64,6 +64,15 @@ t8_geometry_occ_c  *t8_geometry_occ_new (int dimension,
  */
 void                t8_geometry_occ_destroy (t8_geometry_occ_c ** geom);
 
+#if T8_ENABLE_DEBUG
+/** Query whether a given geometry is \ref t8_geometry_occ_c.
+ * \param [in] geometry   A geometry.
+ * \return     True (non-zero) if and only if the geometry is of type \ref t8_geometry_occ_c.
+ * \note       This function is currently only available in debug mode.
+ */
+int                 t8_geom_is_occ (const t8_geometry_c *geometry);
```
[the remark this answers is not in the document]
Comment (holke) [reply src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.h:73]: no, since we may need to use both headers.
Best to declare a function only once and in doubt include both headers.

File: src/t8_cmesh/t8_cmesh_readmshfile.cxx (hunk 1 above)
Comment (holke) [reply src/t8_cmesh/t8_cmesh_readmshfile.cxx:961]: that does not look good.
Can you post the exact call that you are executing and the input file?

**Comment by holke** [comment]
Argh, the cmesh is not committed error is a flaw in my solution.
Need to rethink it completely.

File: src/t8_cmesh/t8_cmesh_readmshfile.cxx (hunk 1 above)
Comment (sandro-elsweijer) [reply src/t8_cmesh/t8_cmesh_readmshfile.cxx:961]: `mpirun -np 8 ./t8_features_curved_meshes -p -f source/naca6412 -o`
[naca6412.zip](https://github.com/DLR-AMR/t8code/files/10259111/naca6412.zip)

Comment (holke) [reply src/t8_cmesh/t8_cmesh_readmshfile.cxx]: image

The same run with the new code :)

Comment (holke) [reply src/t8_cmesh/t8_cmesh_readmshfile.cxx]: Colors are processes

File: src/t8_cmesh/t8_cmesh_readmshfile.cxx [hunk 3]
```diff
@@ -829,14 +835,30 @@ t8_cmesh_msh_file_4_read_eles (t8_cmesh_t cmesh, FILE *fp,
...
+           tree_loop++, tree_count++) {
         /* Read the next line containing tree information */
         retval = t8_cmesh_msh_read_next_line (&line, &linen, fp);
         if (retval < 0) {
           t8_global_errorf ("Premature end of line while reading trees.\n");
           goto die_ele;
         }
         t8_cmesh_set_tree_class (cmesh, tree_count, eclass);
+
+        /* Set the geometry of the tree to be occ or linear */
```
Comment (sandro-elsweijer) [inline src/t8_cmesh/t8_cmesh_readmshfile.cxx:848]: Nice planning ahead here

File: src/t8_cmesh/t8_cmesh_readmshfile.cxx [hunk 4]
```diff
@@ -1710,6 +1767,18 @@ t8_cmesh_from_msh_file (const char *fileprefix, int partition,
...
   t8_cmesh_set_dimension (cmesh, dim);
 
+  /* Register the geometries for the cmesh. */
+  const int           registered_geom_success =
+    t8_cmesh_from_msh_file_register_geometries (cmesh, use_occ_geometry, dim,
+                                                fileprefix, &linear_geometry,
+                                                &occ_geometry);
+  if (!registered_geom_success) {
+    /* Registering failed */
+    t8_debugf ("OCC is not linked. Cannot use OCC geometry.\n");
```
Comment (sandro-elsweijer) [inline src/t8_cmesh/t8_cmesh_readmshfile.cxx:1777]: This should be a `t8_errorf()`. When compiling the code in release, the user has no idea why his cmesh will be destroyed.

File: src/t8_cmesh/t8_cmesh_readmshfile.cxx [hunk 5]
```diff
@@ -1775,12 +1841,8 @@ t8_cmesh_from_msh_file (const char *fileprefix, int partition,
         t8_msh_file_4_read_nodes (file, &num_vertices, &node_mempool);
       if (use_occ_geometry) {
 #if T8_WITH_OCC
-        geometry_occ = t8_geometry_occ_new (dim, fileprefix, "brep_geometry");
-        geometry = geometry_occ;
-        /* Register geometry */
-        t8_cmesh_register_geometry (cmesh, geometry);
         t8_cmesh_msh_file_4_read_eles (cmesh, file, vertices, &vertex_indices,
-                                       dim, geometry_occ);
+                                       dim, linear_geometry, 1, occ_geometry);
```
Comment (sandro-elsweijer) [inline src/t8_cmesh/t8_cmesh_readmshfile.cxx:1845]: Since the occ geometry will be set to the geometry or to NULL by `t8_cmesh_from_msh_file_register_geometries`, we can ditch the if statement and just use
```
t8_cmesh_msh_file_4_read_eles (cmesh, file, vertices, &vertex_indices,
                                       dim, linear_geometry, use_occ_geometry, occ_geometry);
```

**Review by sandro-elsweijer — CHANGES_REQUESTED** [review]
Looks nice, only minor comments. Since the change for the tree geometry is already prepared by you, I will create a follow-up PR implementing this (#353). This should only take an hour so :)

File: src/t8_cmesh/t8_cmesh_readmshfile.cxx (hunk 3 above)
Comment (holke) [reply src/t8_cmesh/t8_cmesh_readmshfile.cxx:848]: You`re welcome :)

File: src/t8_cmesh/t8_cmesh_readmshfile.cxx (hunk 5 above)
Comment (holke) [reply src/t8_cmesh/t8_cmesh_readmshfile.cxx:1845]: DONE

**Comment by holke** [comment]
Should be done. Need to wait if the CI fails again or not...

**Review by sandro-elsweijer — APPROVED** [review]
