### PR TITLE
Documentation: Fix docu t8 types

### LINKED ISSUE #1752: Fix t8_types documentation
# Bug report
Fix all doxygen errors related to files in the t8_types folder
**Describe the bug**
A clear and concise description of what the bug/unexpected behaviour is.

**To Reproduce**
Which command did you run/which function did you call?

**Expected behavior**

**Log files**
- If possible, add any output and error messages that you got
- Please upload the `config.log` file (when building with autotools)
- For failing tests, please upload the `test-suite.log` file (when building with autotools)
- When building with CMake please upload
  - `CMakeCache.txt`
  - `CMakeFiles/CMakeError.log`
  - `CMakeFiles/CMakeOutput.log`
  - `Testing/Temporary/FailedTest.log` (for failing tests)
  - `Testing/Temporary/LastTestsFailed.log` (for failing tests)

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04, Windows 11]
 - Compiler: [e.g., gcc, icc, mpicc]
 - Compiler version: [e.g. the output of 'gcc --version']
 - MPI version (if MPI is used): [The output of 'mpirun --version' or 'mpiexec --version']
 
**Estimated priority**
Which of these is most applicable (remove the others):

"Priority: high"  Should be solved as soon as possible 

"Priority: medium"  Should be solved within half a year 

"Priority: low" Should be solved eventually

**Additional context**

### PR DESCRIPTION
**Pull request by Davknapp**
Closes #1752 

**_All these boxes must be checked by the AUTHOR before requesting review:_**
- [x] The PR is *small enough* to be reviewed easily. If not, consider splitting up the changes in multiple PRs.
- [x] The title starts with one of the following prefixes: `Documentation:`, `Bugfix:`, `Feature:`, `Improvement:` or `Other:`.
- [x] If the PR is related to an issue, make sure to link it.
- [x] The author made sure that, as a reviewer, he/she would check all boxes below.

**_All these boxes must be checked by the REVIEWERS before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is *fully understood, bug free, well-documented and well-structured*.
#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually.
- [ ] The code follows the [t8code coding guidelines](https://github.com/DLR-AMR/t8code/wiki/Coding-Guideline).
- [ ] New source/header files are properly added to the CMake files.
- [ ] The code is well documented. In particular, all function declarations, structs/classes and their members have a proper doxygen documentation.
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue).
#### Tests
- [ ] The code is covered in an existing or new test case using Google Test.
- [ ] The code coverage of the project (reported in the CI) should not decrease. If coverage is decreased, make sure that this is reasonable and acceptable.
- [ ] Valgrind doesn't find any bugs in the new code. [This script](https://github.com/DLR-AMR/t8code/blob/main/scripts/check_valgrind.sh) can be used to check for errors; see also this [wiki article](https://github.com/DLR-AMR/t8code/wiki/Debugging-with-valgrind).

If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually).
#### Scripts and Wiki
- [ ] If a new directory with source files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example or tutorial and a Wiki article.
#### License
- [ ] The author added a BSD statement to `doc/` (or already has one).

### CODE REVIEW

File: src/t8_data/t8_shmem.c [hunk 1]
```diff
@@ -33,15 +33,15 @@
...
+  size_t elem_size;     /*!< Size of one entry in byte. */
+  size_t elem_count;    /*!< Total count of entries. */
+  sc_MPI_Comm comm;     /*!< MPI communicator. */
+  int writing_possible; /*!< True if we can currently write into this array. False if not. */
   int
-    write_start_called; /*< True if t8_shmem_array_start_writing was called and no call to t8_shmem_array_end_writing happened yet. */
+    write_start_called; /*!< True if t8_shmem_array_start_writing was called and no call to t8_shmem_array_end_writing happened yet. */
 #if T8_ENABLE_DEBUG
-  sc_shmem_type_t shmem_type; /*< Shared memory type of the communicator (at time of initializing the array). */
+  sc_shmem_type_t shmem_type; /*!< Shared memory type of the communicator (at time of initializing the array). */
```
Comment (lukasdreyer) [inline src/t8_data/t8_shmem.c]: Please replace `/*!<` by `/**<`

File: src/t8_schemes/t8_scheme.h [hunk 2]
```diff
@@ -744,6 +744,25 @@ t8_element_to_string (const t8_scheme_c *scheme, const t8_eclass_t tree_class, c
...
+* \note If an element was created by \ref t8_element_new then \ref t8_element_init
+* may not be called for it. Thus, \ref t8_element_init should initialize an element
+* in the same way as a call to \ref t8_element_new would.
+* \note Every call to \ref t8_element_init must be matched by a call to \ref t8_element_deinit
+* \see t8_element_deinit
+* \see t8_element_new
+* \see t8_element_is_valid
+*/
+void
+t8_element_init (const t8_scheme_c *scheme, const t8_eclass_t tree_class, const int length, t8_element_t *elem);
```
Comment (lukasdreyer) [inline src/t8_schemes/t8_scheme.h]: Are you sure that this didn't end in an error? `elem` here does not fit `elems` above

File: src/t8_types/t8_type.hxx [hunk 3]
```diff
@@ -69,19 +72,30 @@ class T8Type: public competence<T8Type<T, Parameter, competence...>>... {
...
+  /** Copy constructor */
   constexpr T8Type&
   operator= (const T& value)
   {
     value_ = value;
     return *this;
   }
 
+  /**
+   * \brief Get a reference to the stored value.
```
Comment (lukasdreyer) [inline src/t8_types/t8_type.hxx]: please remove `\brief`
