### PR TITLE
Fix issue 353

### LINKED ISSUE #353: Define linear geometry for non-linked trees in curved meshes.
Currently, the curved occ geometry is assigned to all trees read in by the `.msh` reader. It would give a slight performance boost, if we assign the linear geometry to all unlinked trees in the mesh.

### PR DESCRIPTION
**Pull request by sandro-elsweijer**
**_Describe your changes here:_**
Closes #353
Based on PR #380 

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

- [x] The author added a BSD statement to `doc/` (or already has one)
- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)
- [x] New source/header files are properly added to the Makefiles
- [x] New Datatypes are added to t8indent_custom_datatypes.txt
- [ ] The reviewer executed the new code features at least once and checked the results manually
- [ ] The code is covered in an existing or new test case
- [ ] New tests use the Google Test framework
- [x] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [x] The code is well documented
- [x] All function declarations, structs/classes and their members have a proper doxygen documentation
- [x] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)
- [x] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

### CODE REVIEW

**Comment by holke** [comment]
Sorry i messed up a bit and confused the 353 and 352 branches.
Had to do a force push on this branch to reset my mess.

**Comment by sandro-elsweijer** [comment]
This should also enable us to work on issue #399

File: src/t8_cmesh/t8_cmesh_readmshfile.cxx [hunk 1]
```diff
@@ -1415,6 +1411,20 @@ t8_cmesh_msh_file_4_read_eles (t8_cmesh_t cmesh, FILE *fp,
                                   edge_geometries, 
                                   24 * sizeof(int), 
                                   0);
+          
+          /* Now we set the tree geometry according to the tree linkage status. */
+          char geom_name[BUFSIZ];
```
Comment (holke) [inline src/t8_cmesh/t8_cmesh_readmshfile.cxx:1416]:
```suggestion
          const char *geom_name;
```

File: src/t8_cmesh/t8_cmesh_readmshfile.cxx [hunk 2]
```diff
@@ -1415,6 +1411,20 @@ t8_cmesh_msh_file_4_read_eles (t8_cmesh_t cmesh, FILE *fp,
...
+          if (tree_is_linked) {
+            snprintf (geom_name, BUFSIZ, "%s", 
+                      occ_geometry_base->t8_geom_get_name());
```
Comment (holke) [inline src/t8_cmesh/t8_cmesh_readmshfile.cxx:1419]:
```suggestion
            geom_name = occ_geometry_base->t8_geom_get_name();
```

File: src/t8_cmesh/t8_cmesh_readmshfile.cxx [hunk 3]
```diff
@@ -1415,6 +1411,20 @@ t8_cmesh_msh_file_4_read_eles (t8_cmesh_t cmesh, FILE *fp,
...
+          }
+          else {
+            snprintf (geom_name, BUFSIZ, "%s", 
+                      linear_geometry_base->t8_geom_get_name());
```
Comment (holke) [inline src/t8_cmesh/t8_cmesh_readmshfile.cxx:1423]:
```suggestion
            geom_name = linear_geometry_base->t8_geom_get_name();
```

File: src/t8_cmesh/t8_cmesh_readmshfile.cxx (hunk 1 above)
Comment (holke) [reply src/t8_cmesh/t8_cmesh_readmshfile.cxx:1416]: I do not think that the copying is necessary here.
This should be tested, though.

**Review by holke — CHANGES_REQUESTED** [review]
Looks good.
We currently do not have a test for this.
We do not have any test for reading a .msh file with .brep info i think?
So we should write one.
Minor change is that i dont think the string copying is really necessary and can be done via simple assignment.

**Comment by holke** [comment]
Converted to draft since #380 was reverted.

**Comment by holke** [comment]
@sandro-elsweijer can you please verify whether this is working now (especially on partitioned cmeshes)?
Since Lukas fixed the attribute bug in #444

File: src/t8_cmesh/t8_cmesh_readmshfile.cxx (hunk 1 above)
Comment (sandro-elsweijer) [reply src/t8_cmesh/t8_cmesh_readmshfile.cxx]: I applied and tested the suggestion

File: src/t8_cmesh/t8_cmesh_readmshfile.cxx (hunk 2 above)
Comment (sandro-elsweijer) [reply src/t8_cmesh/t8_cmesh_readmshfile.cxx]: I applied and tested the suggestion

File: src/t8_cmesh/t8_cmesh_readmshfile.cxx (hunk 3 above)
Comment (sandro-elsweijer) [reply src/t8_cmesh/t8_cmesh_readmshfile.cxx]: I applied and tested the suggestion

**Review by holke — APPROVED** [review]
