### PR TITLE
Fix pyramid volume bug

### LINKED ISSUE #438: Pyramid volume bug
grafik

I came across the bug that different volumes are computed for identical pyramid elements. The problem doesn't occur with different element types (e.g. prisms). I have created a branch with a minimal working example of the bug. The example is contained in the file named "t8_practice_file" (https://github.com/jfussbro/t8code/blob/pyra_volume_bug/tutorials/general/t8_practice_file.cxx).

### PR DESCRIPTION
**Pull request by Davknapp**
Simplify volume-computation for pyramids and implements a volume test for all elements. 

Closes #438 

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

- [x] The author added a BSD statement to `doc/` (or already has one)
- [x] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

- [x] All tests pass (in various configurations, this should be executed automatically in a github action)
- [x] New source/header files are properly added to the Makefiles
- [ ] New Datatypes are added to t8indent_custom_datatypes.txt
- [x] The reviewer executed the new code features at least once and checked the results manually
- [x] The code is covered in an existing or new test case
- [x] New tests use the Google Test framework
- [x] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [x] The code is well documented
- [x] All function declarations, structs/classes and their members have a proper doxygen documentation
- [x] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

### CODE REVIEW

File: test/t8_forest/t8_gtest_element_volume.cxx [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+    controll_volume /= 8;
+  }
+  /* Ancestors switch the shape. A tetrahedron a 1/16th of its parents volume. */
+  else {
+    controll_volume /= 16;
+  }
+
+  return controll_volume;
+}
+/* *INDENT-OFF* */
```
Comment (holke) [inline test/t8_forest/t8_gtest_element_volume.cxx:84]: is it really necessary to switch indentation of for the whole function?
Can't you switch it on again after the `TEST_P`?

Comment (holke) [reply test/t8_forest/t8_gtest_element_volume.cxx:84]: If you need to deactivate indentation for such a large block please ensure that the code is indented as closely to the coding guidelines as possible.
For examples `t8_forest_get_tree_num_elements (forest, itree);` instead of `t8_forest_get_tree_num_elements(forest, itree);`

File: test/t8_forest/t8_gtest_element_volume.cxx [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+
+/* *INDENT-ON* */
+/**
+ * Compute the volume of a pyramid descending of a root-pyramid with volume 1/3
+ * 
+ * \param[in] pyra A pyramid
+ * \return The volume of the pyramid 
+ */
+double
+pyramid_controll_volume (t8_dpyramid_t *pyra)
```
Comment (holke) [inline test/t8_forest/t8_gtest_element_volume.cxx:65]: overall in this file `control` instead of `controll`

File: test/t8_forest/t8_gtest_element_volume.cxx [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+  }
+
+  return controll_volume;
+}
+/* *INDENT-OFF* */
+
+TEST_P(t8_forest_volume, volume_check){
+    /* Compute the global number of elements*/
+    const t8_gloidx_t global_num_elements = t8_forest_get_global_num_elements (forest);
+    /* Vertices have a volume of 0. */
```
Comment (holke) [inline test/t8_forest/t8_gtest_element_volume.cxx:89]: please add a comment why pyramids need to be handled separately.

**Comment by holke** [comment]
only made some quick comments. Did not review the code.

**Comment by holke** [comment]
Why did this fail in the old version?
On the first glance there is not much of a difference...

**Comment by Davknapp** [comment]
> Why did this fail in the old version? On the first glance there is not much of a difference...

The array `coordinates` wasn't const in the `tet-volume-computation` and it changed the array in computation of the cross-product. Therefore it was not possible to reset a single coordinate, one had to recompute all of the coordinates. With this fix, one could simplify the computation of the prism-volume, too.

File: test/t8_forest/t8_gtest_element_volume.cxx (hunk 2 above)
Comment (Davknapp) [reply test/t8_forest/t8_gtest_element_volume.cxx:65]: ups. Thanks for the hint.

File: test/t8_forest/t8_gtest_element_volume.cxx [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+ * all elements have volume 1/global_num_elements. */
+/* *INDENT-OFF* */
+class t8_forest_volume:public testing::TestWithParam <std::tuple<t8_eclass_t, int>> {
+    protected:
+        void SetUp () override{
+            eclass = std::get<0>(GetParam ());
+            level = std::get<1>(GetParam ());
+            scheme = t8_scheme_new_default_cxx ();
+            t8_cmesh_t cmesh = t8_cmesh_new_hypercube (eclass, sc_MPI_COMM_WORLD, 0, 0, 0);
+            forest = t8_forest_new_uniform(cmesh, scheme, level, 0, sc_MPI_COMM_WORLD);
```
Comment (ililikakis) [inline test/t8_forest/t8_gtest_element_volume.cxx:46]:
```suggestion
            forest = t8_forest_new_uniform (cmesh, scheme, level, 0, sc_MPI_COMM_WORLD);
```

File: test/t8_forest/t8_gtest_element_volume.cxx [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+ */
+#define epsilon 1e-9
+
+/* Construct a forest of a hypercube with volume 1. If the element are refined uniformly
+ * all elements have volume 1/global_num_elements. */
+/* *INDENT-OFF* */
+class t8_forest_volume:public testing::TestWithParam <std::tuple<t8_eclass_t, int>> {
+    protected:
+        void SetUp () override{
+            eclass = std::get<0>(GetParam ());
```
Comment (ililikakis) [inline test/t8_forest/t8_gtest_element_volume.cxx:42]:
```suggestion
            eclass = std::get<0> (GetParam ());
```

File: test/t8_forest/t8_gtest_element_volume.cxx [hunk 6]
```diff
@@ -0,0 +1,124 @@
...
+            level = std::get<1>(GetParam ());
```
Comment (ililikakis) [inline test/t8_forest/t8_gtest_element_volume.cxx:43]:
```suggestion
            level = std::get<1> (GetParam ());
```

File: test/t8_forest/t8_gtest_element_volume.cxx [hunk 7]
```diff
@@ -0,0 +1,124 @@
...
+            scheme = t8_scheme_new_default_cxx ();
+            t8_cmesh_t cmesh = t8_cmesh_new_hypercube (eclass, sc_MPI_COMM_WORLD, 0, 0, 0);
+            forest = t8_forest_new_uniform(cmesh, scheme, level, 0, sc_MPI_COMM_WORLD);
+        }
+        void TearDown () override {
+            t8_forest_unref(&forest);
```
Comment (ililikakis) [inline test/t8_forest/t8_gtest_element_volume.cxx:49]:
```suggestion
            t8_forest_unref (&forest);
```

**Review by ililikakis — CHANGES_REQUESTED** [review]

**Review by ililikakis — APPROVED** [review]
Looks good :)
